version: '0.1'

services:
  main:
    build: main
    networks:
      - external
      - internal
    ports:
      - 8301:8301
  path_traversal:
    build: path_traversal
    networks:
      - external
      - internal
    ports:
      - 8302:8302
  advanced_path_traversal:
    build: advanced_path_traversal
    networks:
      - external
      - internal
    ports:
      - 8303:8303
  cmdi:
    build: cmdi
    networks:
      - external
      - internal
    ports:
      - 8304:8304
  cmdi_pro_max:
    build: cmdi_pro_max
    networks:
      - external
      - internal
    ports:
      - 8305:8305
  change_email:
    build: change_email
    networks:
      - external
      - internal
    ports:
      - 8306:8306
  php-web:
    build: php-web
    networks:
      - external
      - internal
    ports:
      - 8307:80
  ssti:
    build: ssti
    networks:
      - external
      - internal
    ports:
      - 8308:8308
  xss:
    build: xss
    networks:
      - external
      - internal
    ports:
      - 8309:8309

networks:
  internal:
    internal: true
  external:
