version: '0.1'

services:
  main:
    build: main
    networks:
      - external
      - internal
    ports:
      - 10001:10001
  path_traversal:
    build: path_traversal
    networks:
      - external
      - internal
    ports:
      - 10002:10002
  advanced_path_traversal:
    build: advanced_path_traversal
    networks:
      - external
      - internal
    ports:
      - 10003:10003
  cmdi:
    build: cmdi
    networks:
      - external
      - internal
    ports:
      - 10004:10004
  cmdi_pro_max:
    build: cmdi_pro_max
    networks:
      - external
      - internal
    ports:
      - 10005:10005
  change_email:
    build: change_email
    networks:
      - external
      - internal
    ports:
      - 10006:10006
  php-web:
    build: php-web
    networks:
      - external
      - internal
    ports:
      - 10007:80
  ssti:
    build: ssti
    networks:
      - external
      - internal
    ports:
      - 10008:10008
  xss:
    build: xss
    networks:
      - external
      - internal
    ports:
      - 10009:10009
  prototype_pollution:
    build: prototype_pollution
    networks:
      - external
      - internal
    ports:
      - 10010:10010
  lfi:
    build: lfi
    networks:
      - external
      - internal
    ports:
      - 10011:80

networks:
  internal:
    internal: true
  external:
