version: '0.1'

services:
  main:
    build: main
    networks:
      - external
      - internal
    ports:
      - 8301:5000
  php-web:
    build: php-web
    networks:
      - external
      - internal
    ports:
      - 8302:80

networks:
  internal:
    internal: true
  external:
